

## 1、<span style="color:brown">抛出异常throw：</span>

**1.1、作用：**

```apl
在指定的方法中, 指定的异常
```

**1.2、使用格式：**

```java
throw new xxxException("异常产生的原因")
```

**1.3、注意事项：**

1. throw关键字必须写在***方法的内部***；
2. throw关键字后面`new的对象必须是Exception或者Exception的子类`；
3. throw关键字抛出的异常对象，必须对其进行处理：
   - throw关键字后边创建的是RuntimeException或者是RuntimeException的子类对象，我们可以不处理。默认交给JVM处理(打印异常对象,中断程序)
   - throw关键字后边创建的是编译异常(写代码的时候报错)，我们就必须处理这个异常。要么throws，要么try-catch

**1.4、范例：**

```java
public class Demo01 {
    public static void main(String[] args) {
        /*int[] array1 = null;
        int element1 = getElement(array1,0);
        System.out.println(element1);*/
        int[] array2 = new int[3];
        int element2 = getElement(array2, 3);
        System.out.println(element2);
    }
    public static int getElement(int[] arr, int index){
        if(arr == null){
            throw new NullPointerException("数组为null值");
        }
        if(index<0 || index>arr.length-1){
            throw new ArrayIndexOutOfBoundsException("数组下标越界异常");
        }
        int element = arr[index];
        return element;
    }
}
```

异常1：

```apl
Exception in thread "main" java.lang.NullPointerException: 数组为null值
	at test.Demo01.getElement(Demo01.java:14)
	at test.Demo01.main(Demo01.java:6)
```

异常2：

```apl
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 数组下标越界异常
	at test.Demo01.getElement(Demo01.java:18)
	at test.Demo01.main(Demo01.java:10)
```



## 2、<span style="color:brown">Objects非空判断：</span>

**2.1、概述：**

```apl
Objects工具类是由一些静态方法组成, 这些方法全部是null-safe[空指针安全] 或者 null-tolerant[容忍空指针]
```

**2.2、非空判别方法：**

```java
public static <T> T requireNonNull(T obj)
    查看引用对象是不是null;
```

**2.3、源码：**

```java
public static <T> T requireNonNull(T obj){
    if(obj == null){
        throw new NullPointerException();
    }
    return obj;
}
```

**2.4、范例：**

```java
public class Demo02 {
    public static void main(String[] args) {
        method(null);
    }
    public static void method(Object obj){
        /*if(obj == null){
            throw new NullPointerException("传递对象值为null");
        }*/
        Objects.requireNonNull(obj,"传递对象值为null");
    }
}
```

```apl
Exception in thread "main" java.lang.NullPointerException: 传递对象值为null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at test.Demo02.method(Demo02.java:13)
	at test.Demo02.main(Demo02.java:7)
```



## 3、<span style="color:brown">声明异常throws：</span>异常处理第一种方式！！

**3.1、作用：**

```apl
当方法内部抛出异常, 可以使用throws关键字, 将该异常对象"声明抛出给调用者解决", 最终交给'JVM处理--->中断处理'
```

**3.2、使用格式：**

```java
修饰符 返回值类型 方法名称(参数列表) throws AAAException,BBBException{
    throw new AAAException("异常产生的原因");
    throw new BBBException("异常产生的原因");
    ...
}
```

**3.3、注意事项：**

1. throws必须写在方法声明处；

2. throws关键字后面`new的对象必须是Exception或者Exception的子类`；

3. 如果方法内部抛出多个异常对象，那么throws后面必须声明多个异常对象：

   ```apl
   如果抛出的多个异常对象，存在'子父类关系'，那么只需要"声明父类异常对象"即可
   ```

4. 调用了一个声明异常的方法，解决方式：

   - 继续使用throws声明抛出，然后交给调用者，最终交给JVM处理；
   - 使用try---catch



## 4、<span style="color:brown">捕获异常try---catch：</span>异常处理第二种方式！！

**4.1、格式：**

```java
try{
    【可能产生异常的代码】
}catch(定义一个异常变量，接收try中的异常对象){
    【异常的处理逻辑】
}
...
catch(...){
    ...    
}
```

**4.2、注意事项：**

1. try中可能会抛出多个异常对象，需要多个catch模块来进行接收；
2. 如果try中产生了异常【此时try中的内容从异常处停止运行，直接跳转到catch中】，就会执行catch中的【异常处理逻辑】，在执行完毕之后，继续执行try---catch之后的代码；
3. 如果try中没有产生异常，就直接执行try中的代码，然后继续执行try---catch之后的代码；



## 5、<span style="color:brown">打印异常信息：</span>异常处理第三种方式！！

**5.1、处理异常的方法：**

```java
public String getMessage()
    获取异常的描述、原因;
```

```java
public String toString()
    获取异常的类型和描述信息;
```

```java
public void printStackTrace()
    打印异常的跟踪栈信息，并输出在控制台;
```

**5.2、范例：**

```java
public class Demo03 {
    public static void main(String[] args) {
        try {
            readFile("D:\\a.tx");
        } catch (IOException e) {
            /**
             * System.out.println(e.getMessage());
             * 文件后缀名不对
             */
            
            /**
             * 此处重写了Object类中的toString()方法
             * System.out.println(e.toString());
             * java.io.IOException: 文件后缀名不对
             */
            //System.out.println(e);
            
            /**
             *java.io.IOException: 文件后缀名不对
             *     at test.Demo03.readFile(Demo03.java:26)
             *     at test.Demo03.main(Demo03.java:8)
             */
            e.printStackTrace();
        }
        System.out.println("后续代码");
    }
    public static void readFile(String fileName) throws IOException {
        if(!fileName.endsWith(".txt")){
            throw new IOException("文件后缀名不对");
        }
        System.out.println("路径没有问题，读取文件");
    }
}
```



## 6、<span style="color:brown">finally代码块：</span>

### <span style="color:green">finally代码块中的内容，无论是否出现异常，均可以执行！！！</span>

**6.1、格式：**

```java
try{
    【可能产生异常的代码】
}catch(定义一个异常变量，接收try中的异常对象){
    【异常的处理逻辑】
}
...
catch(...){
    ...    
}
finally{
    
}
```

**6.2、注意事项：**

1. finally代码块无法单独使用，只能与try---catch结合使用；
2. `finally代码块一般用于资源释放`【无论出现异常与否，都要进行资源释放】；

**6.3、范例：**

```java
public class Demo03 {
    public static void main(String[] args) {
        try {
            readFile("D:\\a.tx");
        } catch (IOException e) {
            e.printStackTrace();
        }finally{
            //无论是否出现异常，都会执行
            System.out.println("资源释放");
        }
        System.out.println("后续代码");
    }
    public static void readFile(String fileName) throws IOException {
        if(!fileName.endsWith(".txt")){
            throw new IOException("文件后缀名不对");
        }
        System.out.println("路径没有问题，读取文件");
    }
}
```

```apl
java.io.IOException: 文件后缀名不对
	at test.Demo03.readFile(Demo03.java:19)
	at test.Demo03.main(Demo03.java:8)
资源释放
后续代码
```

