## 1、<span style="color:brown">概述：</span>

**1.1、为什么要自定义异常类?**

```apl
1.在Java开发中, 每一个异常类都只能表达一种异常的情况;
2.在实际开发中, 有时候会产生个别JDK中未定义的情况, 例如: 年龄负数问题、成绩负数问题等;
```

**1.2、如何自定义异常类：**【了解】

1. 格式：

   ```java
   public class XXXException extends Exception / RuntimeException{
       添加一个空参数构造方法;
       添加一个带有异常信息的构造方法;
   }
   ```

2. 自定义一个编译期异常类：`必须处理，要么throws、要么try----catch`

   ```java
   自定义类  extends java.lang.Exception
   ```

3. 自定义一个运行期异常类：`无需处理`

   ```java
   自定义类  extends java.lang.RuntimeException
   ```



## 2、<span style="color:brown">自定义实现类范例：</span>

![案例分析1](https://raw.githubusercontent.com/root-bine/image/main/Typora-image/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%BC%82%E5%B8%B8%E7%B1%BB.png)

**2.1、范例1：Exception**

```java
public class RegisterException extends Exception{
    public RegisterException() {
    }
    public RegisterException(String mesage){
        super(mesage);
    }
}
```

```java
public class Demo05 {
    static String[] usernames = {"张三","李四","王五"};
    public static void main(String[] args) /*throws RegisterException*/{
        Scanner scanner = new Scanner(System.in);
        System.out.println("请输入用户名：");
        String username = scanner.nextLine();
        checkName(username);
    }
    public static void checkName(String username)/*throws RegisterException*/{
        for (String name:usernames) {
            if (name.equals(username)){
                try {
                    throw new RegisterException("该用户名称已占用！！");
                } catch (RegisterException e) {
                    e.printStackTrace();
                    //捕获异常之后，由该语句结束程序运行
                    return;
                }
            }
        }
        //循环结束，仍未找出
        System.out.println("恭喜注册成功！！");
    }
}
```

```apl
请输入用户名：
张三
test.RegisterException: 该用户名称已占用！！
	at test.Demo05.checkName(Demo05.java:17)
	at test.Demo05.main(Demo05.java:11)
```

**2.2、范例2：RuntimeException**

```java
public class RegisterRuntimeException extends RuntimeException{
    public RegisterRuntimeException(){
    }
    public RegisterRuntimeException(String message){
        super(message);
    }
}
```

```java
public class Demo06 {
    static String[] usernames = {"张三", "李四", "王五"};

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println("请输入用户名：");
        String username = scanner.nextLine();
        checkName(username);
    }

    public static void checkName(String username) {
        for (String name : usernames) {
            if (name.equals(username)) {
                throw new RegisterRuntimeException("该用户名称已占用！！");
            }
        }
        //循环结束，仍未找出
        System.out.println("恭喜注册成功！！");
    }
}
```

```apl
请输入用户名：
张三
Exception in thread "main" test.RegisterRuntimeException: 该用户名称已占用！！
	at test.Demo06.checkName(Demo06.java:18)
	at test.Demo06.main(Demo06.java:12)
```

